### PR TITLE
Add support for non-RStudio users

### PR DESCRIPTION
**Pull request by alanocallaghan**

### CODE REVIEW

**Comment by DavZim** [comment]
magick is quite a heavy dependency, is it maybe possible to make it optional (cf https://r-pkgs.org/dependencies.html#guarding-the-use-of-a-suggested-package)?

**Comment by alanocallaghan** [comment]
Heavy in what sense? It only has 3 dependencies

**Comment by DavZim** [comment]
That's true, but Rcpp needs compilation on Unix (and takes a reasonable amount of time) and both curl and Magick itself have system dependencies (not nice on Unix again).

**Comment by alanocallaghan** [comment]
~14% of CRAN directly depends on Rcpp already

**Comment by DavZim** [comment]
And its a very good package that has very good use cases. But regardless, I would try to avoid it as a dependency as I would avoid all strictly unneeded dependencies. 
If you move magick to Depends and use the following above the first call to magick, it would mean the user does not have to have magick installed (or install it) but if the user has it, then it would work anyways.

```R
} else { # your code ...
    if (!requireNamespace("magick", quietly = TRUE))
        stop("You need to have magick installed to view this outside of RStudio") # or similar message
    if (device == "svg") { # your code ...
  #...
```

**Comment by alanocallaghan** [comment]
I dunno, I think "requires curl and imagemagick" and "requires something directly depended on by 15% of CRAN" do not rise to the description of "heavy" or "not nice" when it comes to requirements.

You mean suggests, surely.

Up to the package dev, in my view it's not an unneeded dependency.

And yes, I know how to use dependencies from suggests, thanks though.

**Pull request closed without merging**
